### ISSUE TITLE
[BUG] build failure due to RAFT header change

### ISSUE THREAD

**Issue by wjxiz1992** [NVIDIA/spark-rapids-ml#24]
In this PR: https://github.com/rapidsai/raft/pull/356, raft has changed lots of header file names. We need to modify accordingly.

```
20:18:11  [INFO]      [exec] /usr/local/cuda/bin/nvcc -forward-unknown-to-host-compiler -DCUDA_API_PER_THREAD_DEFAULT_STREAM -DTHRUST_DEVICE_SYSTEM=THRUST_DEVICE_SYSTEM_CUDA -DTHRUST_HOST_SYSTEM=THRUST_HOST_SYSTEM_CPP -Drapidsml_jni_EXPORTS -I/rapids/rmm/include/rmm -I/usr/lib/jvm/java-1.8.0-openjdk/include -I/usr/lib/jvm/java-1.8.0-openjdk/include/linux -I/rapids/raft/cpp/include -I/home/jenkins/agent/workspace/jenkins-rapids-ml-nightly-57-cuda115/native/src/utils -isystem=/usr/local/cuda/include --extended-lambda --generate-code=arch=compute_52,code=[compute_52,sm_52] -Xcompiler=-fPIC -std=c++17 -MD -MT src/CMakeFiles/rapidsml_jni.dir/rapidsml_jni.cu.o -MF src/CMakeFiles/rapidsml_jni.dir/rapidsml_jni.cu.o.d -x cu -c /home/jenkins/agent/workspace/jenkins-rapids-ml-nightly-57-cuda115/native/src/rapidsml_jni.cu -o src/CMakeFiles/rapidsml_jni.dir/rapidsml_jni.cu.o
20:18:11  [INFO]      [exec] /home/jenkins/agent/workspace/jenkins-rapids-ml-nightly-57-cuda115/native/src/rapidsml_jni.cu:25:10: fatal error: raft/matrix/matrix.cuh: No such file or directory
20:18:11  [INFO]      [exec]    25 | #include <raft/matrix/matrix.cuh>
20:18:11  [INFO]      [exec]       |          ^~~~~~~~~~~~~~~~~~~~~~~~
20:18:11  [INFO]      [exec] compilation terminated.
```

**Comment by cjnolet** [comment]
I noticed this issue references recent API changes in RAFT so I wanted to provide a brief note on the current plan to help us stay in alignment. RAFT is currently in the process of exposing a formal public API and hiding irrelevant implementation details from the new APIs.

We are currently in the first of 2 stages, which primarily consists of renaming any .cuh files to .hpp (these are going to be breaking changes as you've already noticed). The second stage will finalize the public API by introducing a new tensor representation format, updating namespaces to align with package categories, and more consistently use the RAFT handle everywhere. The second stage will use a deprecation cycle- the current goal is to add the new completed API functions by 22.04 and remove the old sometime after.
