### ISSUE TITLE
incompatible environment between cuda11.0 and the newer ones

### ISSUE THREAD

**Issue by wjxiz1992** [NVIDIA/spark-rapids-ml#8]
The library libcusolver.so we are using has changed since cuda 11.1. We will build jars for both cuda 11.0 and cuda 11.1(2,3,4). 

We will append classifier at the end of the jar we release. 

cuda11.0 with classifier `cuda11`
cuda11.1~11.4 with classifier `cuda11-2`

Also need to update document for this.

**Comment by pxLi** [comment]
updated classifier `cuda11.2` to `cuda11-2` to follow cudfjni and plugin
